<script lang="ts">
	import { ArrowLeft } from '@lucide/svelte';
	import { Button } from '$lib/components/ui/button';
	import logo from '$lib/assets/logo.png';
	import Footer from '$lib/components/Footer.svelte';
</script>

<div class="flex min-h-screen flex-col">
	<!-- Header -->
	<header class="border-b border-border/40 px-6 py-4">
		<div class="mx-auto flex max-w-6xl items-center justify-between">
			<a href="/" class="flex items-center gap-2">
				<img src={logo} alt="sumgit" class="h-8 w-8 rounded-md" />
				<span class="text-xl font-bold tracking-tight">sumgit</span>
			</a>
			<Button href="/" variant="ghost" class="gap-2">
				<ArrowLeft class="h-4 w-4" />
				Back
			</Button>
		</div>
	</header>

	<!-- Main content -->
	<main class="flex-1 px-6 py-12">
		<div class="mx-auto max-w-3xl">
			<h1 class="mb-2 text-3xl font-bold">Terms of Service</h1>
			<p class="mb-8 text-sm text-muted-foreground">Last updated: January 2025</p>

			<div class="space-y-8 text-muted-foreground">
				<section>
					<h2 class="mb-3 text-xl font-semibold text-foreground">1. Acceptance of Terms</h2>
					<p>
						By accessing or using sumgit ("Service"), you agree to be bound by these Terms of
						Service. If you do not agree to these terms, please do not use the Service.
					</p>
				</section>

				<section>
					<h2 class="mb-3 text-xl font-semibold text-foreground">2. Description of Service</h2>
					<p>
						sumgit is a service that analyzes your GitHub repository commit history to identify and
						extract significant milestones. The Service connects to your GitHub account with
						read-only access to analyze commit metadata including messages, timestamps, and author
						information.
					</p>
				</section>

				<section>
					<h2 class="mb-3 text-xl font-semibold text-foreground">3. GitHub Integration</h2>
					<p class="mb-3">By connecting your GitHub account, you authorize sumgit to:</p>
					<ul class="list-inside list-disc space-y-2 pl-4">
						<li>Access your public and private repository metadata</li>
						<li>Read commit history, messages, and timestamps</li>
						<li>View repository names and descriptions</li>
					</ul>
					<p class="mt-3">
						We request only read-only permissions and cannot modify, push, or delete any content in
						your repositories.
					</p>
				</section>

				<section>
					<h2 class="mb-3 text-xl font-semibold text-foreground">4. User Responsibilities</h2>
					<p class="mb-3">You agree to:</p>
					<ul class="list-inside list-disc space-y-2 pl-4">
						<li>Provide accurate information when creating an account</li>
						<li>Maintain the security of your account credentials</li>
						<li>Only connect repositories you have the right to analyze</li>
						<li>Not use the Service for any unlawful purpose</li>
						<li>Not attempt to circumvent any security features of the Service</li>
					</ul>
				</section>

				<section>
					<h2 class="mb-3 text-xl font-semibold text-foreground">5. Intellectual Property</h2>
					<p>
						You retain all rights to your code and commit history. sumgit does not claim ownership
						of any content from your repositories. The milestones and summaries generated by our AI
						analysis are provided for your use but may not be redistributed commercially without
						permission.
					</p>
				</section>

				<section>
					<h2 class="mb-3 text-xl font-semibold text-foreground">6. Limitation of Liability</h2>
					<p>
						The Service is provided "as is" without warranties of any kind. We are not liable for
						any damages arising from your use of the Service, including but not limited to direct,
						indirect, incidental, or consequential damages.
					</p>
				</section>

				<section>
					<h2 class="mb-3 text-xl font-semibold text-foreground">7. Service Modifications</h2>
					<p>
						We reserve the right to modify, suspend, or discontinue the Service at any time without
						notice. We may also update these Terms of Service, and continued use of the Service
						constitutes acceptance of any changes.
					</p>
				</section>

				<section>
					<h2 class="mb-3 text-xl font-semibold text-foreground">8. Termination</h2>
					<p>
						You may disconnect your GitHub account and stop using the Service at any time. We
						reserve the right to terminate or suspend your access to the Service for violations of
						these terms or for any other reason at our discretion.
					</p>
				</section>

				<section>
					<h2 class="mb-3 text-xl font-semibold text-foreground">9. Contact</h2>
					<p>
						For questions about these Terms of Service, please contact us at
						<a href="mailto:support@codedeen.com" class="text-primary hover:underline">
							support@codedeen.com
						</a>.
					</p>
				</section>
			</div>
		</div>
	</main>

	<Footer />
</div>
